# Generated by Django 2.0.5 on 2018-05-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_auto_20180526_0237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustom',
            new_name='User',
        ),
    ]
